export const surpriseMePrompts = [
    'Armchair',
    'a checkers',
    'teddy bears ',
    ' a humanoid robot',
    'panda',
    "a macro 35mm",
    ' tropical fish ',
    'an astronaut ',
    'an oil painting ',
    'a stained glass',
    'a pencil ',
    'a sunlit ',
    'ahamburger',
    '"a sea otter ',
    'a spaceship',
    'a fox',
    'a bowl of soup ',
    'A toy robot ',
    'A synthwave ',
    'Two futuristic towers',
    'A rainbow ',
    'A comic book ',
    'A centered explosion ',
    'A Samoyed dog ',
    'A  monster ',
    "A Michelangelo",
    'A Samurai.',
    'A photography',
    'A dragon',
    'A another dimension',
    'Spongebob Squarepants ',
    'A velociraptor ',
    'A 50mm lens',
    'A animated movie',
    'A neon lights',
    'The  Japanese Anime',
    'A hamburger',
    'A Cyberpunk',
    'An astronaut',
    'A Dinosaur photography',
    'A Man',
    'A cyborg ',
    'Dracula ',
    'Synthwave aeroplane',
    ' Tokyo',
    'A Space Shuttle ',
  ];